services:
  - type: web
    name: family-shopping-list
    runtime: go
    plan: free
    buildCommand: go build -o app main.go
    startCommand: ./app
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: sqlite://./shopping_list.db
      - key: NEWS_API_KEY
        value: 4623d584d9db4beeafb27c2ec38b2060
